version: "3.9"

services:
  grafana:
    image: grafana/grafana:8.5.3-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.7.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - /home/user/grafana-loki-promtail/loki-config.yaml:/etc/loki/local-config.yaml
      - /home/user/grafana-loki-promtail/loki-data:/loki
      - /home/user/grafana-loki-promtail/loki-wal:/wal
      - /home/user/grafana-loki-promtail/loki-compactor:/compactor

  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id
      - /home/user/grafana-loki-promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  grafana-data:
